"""removed images

Revision ID: ee21edcaa2ac
Revises: 816b2853c2b0
Create Date: 2020-12-28 23:00:10.585146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee21edcaa2ac'
down_revision = '816b2853c2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts') as batch_op:
        batch_op.drop_column('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
